version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: coderadar-db
    environment:
      POSTGRES_USER: coderadar
      POSTGRES_PASSWORD: coderadar
      POSTGRES_DB: coderadar
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: coderadar-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
